// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'0d60c8c8f273f38c3ae51484f6a3c1df0b6ed91bbd3c241e849170d9be420811'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Eventos: {
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
    };
    readonly JogosColetivos: {
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_ganhador: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_turma_01: CodecTypes['pg/int4@1']['output'];
      readonly id_turma_02: CodecTypes['pg/int4@1']['output'];
      readonly modalidadeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly JogosIndividuais: {
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_ganhador: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_participante_01: CodecTypes['pg/int4@1']['output'];
      readonly id_participante_02: CodecTypes['pg/int4@1']['output'];
      readonly modalidadeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Modalidades: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly pontos: CodecTypes['pg/int4@1']['output'];
    };
    readonly Moderador: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly login: CodecTypes['pg/text@1']['output'];
      readonly senha: CodecTypes['pg/text@1']['output'];
    };
    readonly Participantes: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly turmaId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Turmas: {
      readonly curso: 'INFORMÁTICA' | 'MINERAÇÃO';
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly serie: CodecTypes['pg/int4@1']['output'];
      readonly turno: 'MATUTINO' | 'VESPERTINO';
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Eventos: {
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
    };
    readonly JogosColetivos: {
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_ganhador: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_turma_01: CodecTypes['pg/int4@1']['input'];
      readonly id_turma_02: CodecTypes['pg/int4@1']['input'];
      readonly modalidadeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly JogosIndividuais: {
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_ganhador: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_participante_01: CodecTypes['pg/int4@1']['input'];
      readonly id_participante_02: CodecTypes['pg/int4@1']['input'];
      readonly modalidadeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Modalidades: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly pontos: CodecTypes['pg/int4@1']['input'];
    };
    readonly Moderador: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly login: CodecTypes['pg/text@1']['input'];
      readonly senha: CodecTypes['pg/text@1']['input'];
    };
    readonly Participantes: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly turmaId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Turmas: {
      readonly curso: 'INFORMÁTICA' | 'MINERAÇÃO';
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly serie: CodecTypes['pg/int4@1']['input'];
      readonly turno: 'MATUTINO' | 'VESPERTINO';
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Eventos: {
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
    };
    readonly JogosColetivos: {
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_ganhador: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_turma_01: CodecTypes['pg/int4@1']['output'];
      readonly id_turma_02: CodecTypes['pg/int4@1']['output'];
      readonly modalidadeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly JogosIndividuais: {
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_ganhador: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_participante_01: CodecTypes['pg/int4@1']['output'];
      readonly id_participante_02: CodecTypes['pg/int4@1']['output'];
      readonly modalidadeId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Modalidades: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly pontos: CodecTypes['pg/int4@1']['output'];
    };
    readonly Moderador: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly login: CodecTypes['pg/text@1']['output'];
      readonly senha: CodecTypes['pg/text@1']['output'];
    };
    readonly Participantes: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly turmaId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Turmas: {
      readonly curso: 'INFORMÁTICA' | 'MINERAÇÃO';
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly serie: CodecTypes['pg/int4@1']['output'];
      readonly turno: 'MATUTINO' | 'VESPERTINO';
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Eventos: {
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
    };
    readonly JogosColetivos: {
      readonly date: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_ganhador: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_turma_01: CodecTypes['pg/int4@1']['input'];
      readonly id_turma_02: CodecTypes['pg/int4@1']['input'];
      readonly modalidadeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly JogosIndividuais: {
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_ganhador: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_participante_01: CodecTypes['pg/int4@1']['input'];
      readonly id_participante_02: CodecTypes['pg/int4@1']['input'];
      readonly modalidadeId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Modalidades: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly pontos: CodecTypes['pg/int4@1']['input'];
    };
    readonly Moderador: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly login: CodecTypes['pg/text@1']['input'];
      readonly senha: CodecTypes['pg/text@1']['input'];
    };
    readonly Participantes: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly turmaId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Turmas: {
      readonly curso: 'INFORMÁTICA' | 'MINERAÇÃO';
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly serie: CodecTypes['pg/int4@1']['input'];
      readonly turno: 'MATUTINO' | 'VESPERTINO';
    };
  };
};

export namespace Models {
  export type public_Eventos = {
    data: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_JogosColetivos = {
    date: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    id_ganhador: CodecTypes['pg/int4@1']['output'] | null;
    id_turma_01: CodecTypes['pg/int4@1']['output'];
    id_turma_02: CodecTypes['pg/int4@1']['output'];
    modalidadeId: CodecTypes['pg/int4@1']['output'];
    ganhador: public_Turmas | null;
    modalidade: public_Modalidades;
    turma_01: public_Turmas;
    turma_02: public_Turmas;
    readonly [RelationKeys]?: 'ganhador' | 'modalidade' | 'turma_01' | 'turma_02';
  };
  export type public_JogosIndividuais = {
    data: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    id_ganhador: CodecTypes['pg/int4@1']['output'] | null;
    id_participante_01: CodecTypes['pg/int4@1']['output'];
    id_participante_02: CodecTypes['pg/int4@1']['output'];
    modalidadeId: CodecTypes['pg/int4@1']['output'];
    ganhador: public_Participantes | null;
    modalidade: public_Modalidades;
    participante01: public_Participantes;
    participante02: public_Participantes;
    readonly [RelationKeys]?: 'ganhador' | 'modalidade' | 'participante01' | 'participante02';
  };
  export type public_Modalidades = {
    id: CodecTypes['pg/int4@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    pontos: CodecTypes['pg/int4@1']['output'];
    jogosColetivos: public_JogosColetivos[];
    jogosIndividuais: public_JogosIndividuais[];
    readonly [RelationKeys]?: 'jogosColetivos' | 'jogosIndividuais';
  };
  export type public_Moderador = {
    id: CodecTypes['pg/int4@1']['output'];
    login: CodecTypes['pg/text@1']['output'];
    senha: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Participantes = {
    id: CodecTypes['pg/int4@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    turmaId: CodecTypes['pg/int4@1']['output'];
    jogos01: public_JogosIndividuais[];
    jogos02: public_JogosIndividuais[];
    turma: public_Turmas;
    vitorias: public_JogosIndividuais[];
    readonly [RelationKeys]?: 'jogos01' | 'jogos02' | 'turma' | 'vitorias';
  };
  export type public_Turmas = {
    curso: 'INFORMÁTICA' | 'MINERAÇÃO';
    id: CodecTypes['pg/int4@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    serie: CodecTypes['pg/int4@1']['output'];
    turno: 'MATUTINO' | 'VESPERTINO';
    JogosTurma1: public_JogosColetivos[];
    JogosTurma2: public_JogosColetivos[];
    participante: public_Participantes[];
    vitorias: public_JogosColetivos[];
    readonly [RelationKeys]?: 'JogosTurma1' | 'JogosTurma2' | 'participante' | 'vitorias';
  };
}

export declare const models: {
  public: {
    Eventos: Models.public_Eventos;
    JogosColetivos: Models.public_JogosColetivos;
    JogosIndividuais: Models.public_JogosIndividuais;
    Modalidades: Models.public_Modalidades;
    Moderador: Models.public_Moderador;
    Participantes: Models.public_Participantes;
    Turmas: Models.public_Turmas;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Eventos: {
              columns: {
                readonly data: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly JogosColetivos: {
              columns: {
                readonly date: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly id_ganhador: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly id_turma_01: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_turma_02: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly modalidadeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'JogosColetivos_id_ganhador_idx_f2baa3c7';
                  readonly prefix: 'JogosColetivos_id_ganhador_idx';
                  readonly columns: readonly ['id_ganhador'];
                  readonly unique: false;
                },
                {
                  readonly name: 'JogosColetivos_id_turma_01_idx_28888e28';
                  readonly prefix: 'JogosColetivos_id_turma_01_idx';
                  readonly columns: readonly ['id_turma_01'];
                  readonly unique: false;
                },
                {
                  readonly name: 'JogosColetivos_id_turma_02_idx_c49a8736';
                  readonly prefix: 'JogosColetivos_id_turma_02_idx';
                  readonly columns: readonly ['id_turma_02'];
                  readonly unique: false;
                },
                {
                  readonly name: 'JogosColetivos_modalidadeId_idx_66444aed';
                  readonly prefix: 'JogosColetivos_modalidadeId_idx';
                  readonly columns: readonly ['modalidadeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'JogosColetivos';
                    readonly columns: readonly ['modalidadeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Modalidades';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'JogosColetivos';
                    readonly columns: readonly ['id_turma_01'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Turmas';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'JogosColetivos';
                    readonly columns: readonly ['id_turma_02'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Turmas';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'JogosColetivos';
                    readonly columns: readonly ['id_ganhador'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Turmas';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly JogosIndividuais: {
              columns: {
                readonly data: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly id_ganhador: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly id_participante_01: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_participante_02: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly modalidadeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'JogosIndividuais_id_ganhador_idx_f2baa3c7';
                  readonly prefix: 'JogosIndividuais_id_ganhador_idx';
                  readonly columns: readonly ['id_ganhador'];
                  readonly unique: false;
                },
                {
                  readonly name: 'JogosIndividuais_id_participante_01_idx_403261a7';
                  readonly prefix: 'JogosIndividuais_id_participante_01_idx';
                  readonly columns: readonly ['id_participante_01'];
                  readonly unique: false;
                },
                {
                  readonly name: 'JogosIndividuais_id_participante_02_idx_db9d20ae';
                  readonly prefix: 'JogosIndividuais_id_participante_02_idx';
                  readonly columns: readonly ['id_participante_02'];
                  readonly unique: false;
                },
                {
                  readonly name: 'JogosIndividuais_modalidadeId_idx_66444aed';
                  readonly prefix: 'JogosIndividuais_modalidadeId_idx';
                  readonly columns: readonly ['modalidadeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'JogosIndividuais';
                    readonly columns: readonly ['modalidadeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Modalidades';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'JogosIndividuais';
                    readonly columns: readonly ['id_participante_01'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Participantes';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'JogosIndividuais';
                    readonly columns: readonly ['id_participante_02'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Participantes';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'JogosIndividuais';
                    readonly columns: readonly ['id_ganhador'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Participantes';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Modalidades: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pontos: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Moderador: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly login: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly senha: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['login'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Participantes: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly turmaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Participantes_turmaId_idx_4f1eb1a9';
                  readonly prefix: 'Participantes_turmaId_idx';
                  readonly columns: readonly ['turmaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Participantes';
                    readonly columns: readonly ['turmaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Turmas';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Turmas: {
              columns: {
                readonly curso: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly serie: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly turno: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'MATUTINO'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Cursos: {
              readonly kind: 'valueSet';
              readonly values: readonly ['INFORMÁTICA', 'MINERAÇÃO'];
            };
            readonly Turnos: {
              readonly kind: 'valueSet';
              readonly values: readonly ['MATUTINO', 'VESPERTINO'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Eventos: { readonly namespace: 'public' & NamespaceId; readonly model: 'Eventos' };
    readonly JogosColetivos: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'JogosColetivos';
    };
    readonly JogosIndividuais: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'JogosIndividuais';
    };
    readonly Modalidades: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Modalidades';
    };
    readonly Moderador: { readonly namespace: 'public' & NamespaceId; readonly model: 'Moderador' };
    readonly Participantes: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Participantes';
    };
    readonly Turmas: { readonly namespace: 'public' & NamespaceId; readonly model: 'Turmas' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Eventos: {
            readonly fields: {
              readonly data: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Eventos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly data: { readonly column: 'data' };
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
              };
            };
          };
          readonly JogosColetivos: {
            readonly fields: {
              readonly date: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_ganhador: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_turma_01: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_turma_02: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly modalidadeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly ganhador: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Turmas';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id_ganhador'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly modalidade: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Modalidades';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['modalidadeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly turma_01: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Turmas';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_turma_01'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly turma_02: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Turmas';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_turma_02'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'JogosColetivos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly date: { readonly column: 'date' };
                readonly id: { readonly column: 'id' };
                readonly id_ganhador: { readonly column: 'id_ganhador' };
                readonly id_turma_01: { readonly column: 'id_turma_01' };
                readonly id_turma_02: { readonly column: 'id_turma_02' };
                readonly modalidadeId: { readonly column: 'modalidadeId' };
              };
            };
          };
          readonly JogosIndividuais: {
            readonly fields: {
              readonly data: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_ganhador: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_participante_01: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_participante_02: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly modalidadeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly ganhador: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Participantes';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id_ganhador'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly modalidade: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Modalidades';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['modalidadeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly participante01: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Participantes';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_participante_01'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly participante02: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Participantes';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_participante_02'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'JogosIndividuais';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly data: { readonly column: 'data' };
                readonly id: { readonly column: 'id' };
                readonly id_ganhador: { readonly column: 'id_ganhador' };
                readonly id_participante_01: { readonly column: 'id_participante_01' };
                readonly id_participante_02: { readonly column: 'id_participante_02' };
                readonly modalidadeId: { readonly column: 'modalidadeId' };
              };
            };
          };
          readonly Modalidades: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pontos: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly jogosColetivos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JogosColetivos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['modalidadeId'];
                };
              };
              readonly jogosIndividuais: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JogosIndividuais';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['modalidadeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Modalidades';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly pontos: { readonly column: 'pontos' };
              };
            };
          };
          readonly Moderador: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly login: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly senha: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Moderador';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly login: { readonly column: 'login' };
                readonly senha: { readonly column: 'senha' };
              };
            };
          };
          readonly Participantes: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly turmaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly jogos01: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JogosIndividuais';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_participante_01'];
                };
              };
              readonly jogos02: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JogosIndividuais';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_participante_02'];
                };
              };
              readonly turma: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Turmas';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['turmaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly vitorias: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JogosIndividuais';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_ganhador'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Participantes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly turmaId: { readonly column: 'turmaId' };
              };
            };
          };
          readonly Turmas: {
            readonly fields: {
              readonly curso: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly serie: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly turno: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly JogosTurma1: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JogosColetivos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_turma_01'];
                };
              };
              readonly JogosTurma2: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JogosColetivos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_turma_02'];
                };
              };
              readonly participante: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Participantes';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['turmaId'];
                };
              };
              readonly vitorias: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JogosColetivos';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_ganhador'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Turmas';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly curso: { readonly column: 'curso' };
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly serie: { readonly column: 'serie' };
                readonly turno: { readonly column: 'turno' };
              };
            };
          };
        };
        readonly enum: {
          readonly Cursos: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'INFORMÁTICA'; readonly value: 'INFORMÁTICA' },
              { readonly name: 'MINERAÇÃO'; readonly value: 'MINERAÇÃO' },
            ];
          };
          readonly Turnos: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'MATUTINO'; readonly value: 'MATUTINO' },
              { readonly name: 'VESPERTINO'; readonly value: 'VESPERTINO' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
